BookStore/BookStore/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin")]
    public class DashboardController : Controller
    {
        // GET: DashboardController
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: DashboardController/Details/5
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: DashboardController/Create
        [Route("create")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: DashboardController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DashboardController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DashboardController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DashboardController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DashboardController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using BookStore.Models;
using BookStore.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ILanguageRepository _LanguageRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        [ViewData]
        public string Title { get; set; }

        public BookController(IBookRepository bookRepository, ILanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _LanguageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<ViewResult> GetAllBooks()
        {
            var data = await _bookRepository.GetAllBooks();
            return View(data);
        }

        //public List<BookModel> GetAllBooks()
        //{
        //    return _bookRepository.GetAllBooks();
        //}

        public async Task<ViewResult> GetBook(int id)
        {
            var data = await _bookRepository.GetBookById(id);
            return View(data);
        }
        //public BookModel GetBook(int id)
        //{
        //    return _bookRepository.GetBookById(id);
        //}

        public List<BookModel> BookSearch(string bookName, string authorName)
        {
            return _bookRepository.SearchBook(bookName,authorName);
        }
        [Authorize]
        public async Task<ViewResult> BookSubmit(bool isSuccess = false)
        {
            //var model = new BookModel();
            //model.Language = await _LanguageRepository.GetLanguages();
            //ViewBag.Language = await _LanguageRepository.GetLanguages();
            //ViewBag.Language = new SelectList(await _LanguageRepository.GetLanguages(), "Id", "Name");
            ViewBag.IsSuccess = isSuccess;
            Title = "BookSubmit";
            //return View("BookSubmit", model);
            return View("BookSubmit");
        }


        [HttpPost]
        public async Task<IActionResult> BookSubmit(BookModel bookmodel)
        {
            Title = "BookSubmit";
            if (ModelState.IsValid)
            {
                if(bookmodel.CoverPhoto != null && bookmodel.CoverPhoto.Length > 0)
                {
                    if(bookmodel.CoverPhoto.ContentType != "image/jpeg" && bookmodel.CoverPhoto.ContentType != "image/png")
                    {  
                        ModelState.AddModelError("CoverPhoto", "Only images with jpeg or png formats are allowed!");
                        return View("BookSubmit");
                    }
                    else
                    {
                        string folder = "books/cover/";
                      bookmodel.CoverImageUrl =  await UploadImage(folder, bookmodel.CoverPhoto);
                    }
                }
                if (bookmodel.GalleryFiles != null)
                {
                    string folder = "books/gallery/";
                    bookmodel.Gallery = new List<GalleryModel>();
                    foreach (var file in bookmodel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.Name,
                            URL = await UploadImage(folder, file)
                        };
                        bookmodel.Gallery.Add(gallery);
                        
                    }
                }
                if(bookmodel.BookPdf != null)
                {
                    string folder = "books/pdf/";
                    bookmodel.BookPdfUrl = await UploadImage(folder, bookmodel.BookPdf);
                }
                int id = await _bookRepository.AddNewBook(bookmodel);
                if (id > 0)
                {
                    return RedirectToAction("BookSubmit", new { isSuccess = true });
                }
            }

            //ViewBag.Language = new SelectList(await _LanguageRepository.GetLanguages(), "Id", "Name");

            return View("BookSubmit");
            //model.Language = await _LanguageRepository.GetLanguages();
            //ViewBag.Language = await _LanguageRepository.GetLanguages();
            //ViewBag.LanguageConnectionId = new SelectList(await _LanguageRepository.GetLanguages(), "Id", "Name");
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }
    }
}

BookStore/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | Application</title>
    @*

        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.esm.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.esm.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>

                        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
                        <link href="~/lib/bootstrap/css/bootstrap.rtl.min.css" rel="stylesheet" />
                        <link href="~/lib/bootstrap/css/bootstrap.rtl.css" rel="stylesheet" />
                        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />*@
    @*<environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>

    <environment exclude="Development">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">

        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>

    </environment>*@
    <link href="~/css/Site.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <script 
            defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
    </script>

</head>

<body>
    <partial name="_header"/>
    <main>
        @RenderBody()
    </main>
    <partial name="_footer"/>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>
</body>

</html>

BookStore/BookStore/Views/Shared/_LoginInfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager

@if (_signInManager.IsSignedIn(User)) {
    
 <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Hello @User.FindFirst("UserFirstName").Value
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a></li>
        <li><a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">Change Password</a></li>
    </ul>
 </div>
 }
else {<li class="nav-item">
    <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Login</a>
    <a class="btn btn-primary" asp-controller="Account" asp-action="Signup">Register</a>
</li> }

BookStore/BookStore/Views/Shared/_bookThumbnail.cshtml
@model BookModel

<div class="card mb-4 shadow-sm">
    <img src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/images/561dfe3e-e5f8-415c-9b26-fbdf94897722-cover.png" : Model.CoverImageUrl)" class="card-img-top img-thumbnail">
    <div class="card-body">
        <h3 class="card-title">@(string.IsNullOrEmpty(Model.Title) ? "Title is not availabile" : Model.Title)</h3>
        <p class="card-text">@(string.IsNullOrEmpty(Model.Description) ? "Description is not availabile" : Model.Description)</p>
        <div class="d-flex justify-content-between align-items-center ">
            <div class="btn-group">
                <a asp-controller="Book" asp-action="GetBook" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-secondary">Click For More!</a>
            </div>
            <small class="text-muted">@(string.IsNullOrEmpty(Model.Author) ? "NA" : Model.Author)</small>
        </div>
    </div>
</div>

BookStore/BookStore/Views/Shared/_footer.cshtml
<footer class="border-top text-muted text-center position-fixed bottom-0 w-100">
    <div class="container mt-2">
        Copyright &copy; BookStore @DateTime.Now.Year
    </div>
</footer>

BookStore/BookStore/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">BookStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Aboutus">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="ContactUs">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Book" asp-action="GetAllBooks">All Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Book" asp-action="BookSubmit">Submit Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="index">Admin</a>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav">
                <partial name="_LoginInfo"></partial>
            </ul>
        </div>
    </nav>
</header>