BookStore/BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using BookStore.Models;
using Microsoft.Extensions.Configuration;
using BookStore.Services;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public HomeController(IUserService userService, IEmailService emailService)
        {
            _userService = userService;
            _emailService = emailService;
        }

        [ViewData]
        public BookModel Book { get; set; }

        [ViewData]
        public string Title { get; set; }
        public async Task<IActionResult> index()
        {
            //UserEmailOptions options = new UserEmailOptions()
            //{
            //    ToEmails = new List<string>() { "test@gmail.com" },
            //    PlaceHolders= new List<KeyValuePair<string, string>>
            //    {
            //        new KeyValuePair<string, string>("{{UserName}}", "Mohammad")
            //    }
            //};

            //await _emailService.SendTestEmail(options);

            var userId = _userService.GetUserId();
            var isLoggedIn = _userService.IsAuthenticated();

            Title = "Home";
            //Book = new BookModel(){Id = 1, Title = "PHP"};
            return View();
        }
        public ViewResult Aboutus()
        {
            Title = "About Us";
            return View();
        }
        public ViewResult ContactUs()
        {
            Title = "Contact Us";
            return View();
        }
        

    }
}

BookStore/BookStore/ViewComponents/TopBooksViewComponent.cs
using BookStore.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookStore.ViewComponents
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var topbooks = await _bookRepository.GetTopBooksAsync(count);
            return View(topbooks);
        }
    }
}

BookStore/BookStore/Views/Home/Aboutus.cshtml
<h1>this page introduces BookStore to our customers.</h1>

BookStore/BookStore/Views/Home/ContactUs.cshtml
<h1>ContactUs</h1>

BookStore/BookStore/Views/Home/Index.cshtml
@using BookStore.Models
@inject BookStore.Repository.IBookRepository _bookRepository
@{
    var BookInfo = ViewData["book"] as BookModel;
}


<section class="jumbotron text-center  mt-5">
<div class="container">
<h1 class="text-uppercase">Welcome to the bookstore @ViewData["CustomProperty"] </h1>


    <p class="lead text-muted">
        Lorem ipsum odor amet, consectetuer adipiscing elit. Consectetur egestas rutrum conubia egestas odio. Cursus venenatis amet erat penatibus etiam; mauris mus. Velit vel primis senectus nec eleifend pharetra mattis. Purus ultrices rhoncus est blandit cubilia diam facilisis. Mus litora tellus est libero tellus facilisis orci. Maximus iaculis leo mi primis sagittis eget.
    </p>
    <p>
        
        <a href="#" class="btn btn-primary my-2">Search Books</a>
    </p>
</div>
</section>

<div class="py-4 bg-light">
    <div class="container">
        <h3>Top Books</h3>
            @await Component.InvokeAsync("TopBooks", new {count=6})
    </div>
</div>